import React, { useState } from 'react'
import { DashboardLayout } from '@components/common/DashboardLayout'
import { Card, CardHeader, CardBody } from '@components/common/Card'
import { Button } from '@components/common/Button'
import { Input } from '@components/common/Input'
import { useNavigate } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup'
import { User, Mail, Phone, Briefcase, Calendar, DollarSign, AlertCircle, Copy, CheckCircle } from 'lucide-react'
import api from '@services/api'
import { USER_ROLES } from '@utils/constants'

const addEmployeeSchema = yup.object().shape({
  name: yup.string().required('Name is required').min(2, 'Name must be at least 2 characters'),
  email: yup.string().required('Email is required').email('Invalid email format'),
  phone: yup.string().required('Phone is required').matches(/^[0-9]{10,15}$/, 'Phone must be 10-15 digits'),
  role: yup.string().required('Role is required'),
  designation: yup.string().required('Designation is required'),
  department: yup.string().required('Department is required'),
  joiningDate: yup.string().required('Joining date is required'),
  salary: yup.number().required('Salary is required').positive('Salary must be positive'),
  address: yup.string(),
  // Password is now auto-generated by backend
})

function AddEmployee() {
  const navigate = useNavigate()
  const [serverError, setServerError] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [credentials, setCredentials] = useState(null)
  const [copied, setCopied] = useState(false)

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(addEmployeeSchema),
  })

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const copyAllCredentials = () => {
    const text = `Login ID: ${credentials.loginId}\nPassword: ${credentials.password}\n\nPlease change this password on first login.`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const onSubmit = async (data) => {
    try {
      setIsSubmitting(true)
      setServerError('')
      setCredentials(null)

      console.log('Submitting employee data:', data)

      const response = await api.post('/employees', data)

      console.log('Employee created successfully:', response.data)

      // Show generated credentials
      if (response.data.loginCredentials) {
        setCredentials(response.data.loginCredentials)
      } else {
        console.error('No login credentials in response:', response.data)
        setServerError('Employee created but credentials not returned. Please contact support.')
      }
    } catch (error) {
      console.error('Error creating employee:', error.response || error)
      
      // Extract error message
      let errorMessage = 'Failed to add employee. Please try again.'
      
      if (error.response?.data) {
        if (error.response.data.message) {
          errorMessage = error.response.data.message
        } else if (error.response.data.errors && Array.isArray(error.response.data.errors)) {
          errorMessage = error.response.data.errors.map(e => e.message).join(', ')
        }
      }
      
      setServerError(errorMessage)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <DashboardLayout>
      <div className="max-w-4xl">
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-gray-900">Add New Employee</h1>
          <p className="text-gray-600 mt-1">Create a new employee account</p>
        </div>

        {serverError && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start">
            <AlertCircle className="w-5 h-5 text-danger mr-3 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-danger">{serverError}</p>
          </div>
        )}

        {/* Success - Show Generated Credentials */}
        {credentials && (
          <Card className="mb-6 border-green-200 bg-green-50">
            <CardHeader>
              <div className="flex items-center">
                <CheckCircle className="w-6 h-6 text-green-600 mr-2" />
                <h2 className="text-lg font-semibold text-green-900">Employee Created Successfully!</h2>
              </div>
            </CardHeader>
            <CardBody>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <p className="text-sm text-green-800">
                    {credentials.message}
                  </p>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={copyAllCredentials}
                    className="flex items-center space-x-2"
                  >
                    {copied ? (
                      <>
                        <CheckCircle className="w-4 h-4" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        <span>Copy All</span>
                      </>
                    )}
                  </Button>
                </div>
                
                <div className="bg-white border border-green-200 rounded-lg p-4 space-y-3">
                  <div>
                    <label className="text-sm font-medium text-gray-700">Login ID</label>
                    <div className="flex items-center mt-1">
                      <code className="flex-1 bg-gray-50 px-3 py-2 rounded border border-gray-200 text-sm">
                        {credentials.loginId}
                      </code>
                      <button
                        type="button"
                        onClick={() => copyToClipboard(credentials.loginId)}
                        className="ml-2 p-2 text-gray-600 hover:text-odoo-primary transition-colors"
                        title="Copy Login ID"
                      >
                        <Copy className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                  
                  <div>
                    <label className="text-sm font-medium text-gray-700">Password (Auto-generated)</label>
                    <div className="flex items-center mt-1">
                      <code className="flex-1 bg-gray-50 px-3 py-2 rounded border border-gray-200 text-sm font-mono">
                        {credentials.password}
                      </code>
                      <button
                        type="button"
                        onClick={() => copyToClipboard(credentials.password)}
                        className="ml-2 p-2 text-gray-600 hover:text-odoo-primary transition-colors"
                        title="Copy Password"
                      >
                        <Copy className="w-5 h-5" />
                      </button>
                    </div>
                  </div>
                </div>

                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
                  <p className="text-sm text-yellow-800">
                    ⚠️ <strong>Important:</strong> The employee will be required to change this password on first login.
                  </p>
                </div>

                <div className="flex justify-end space-x-3 pt-2">
                  <Button
                    variant="outline"
                    onClick={() => window.location.reload()}
                  >
                    Add Another Employee
                  </Button>
                  <Button
                    variant="primary"
                    onClick={() => navigate('/employees')}
                  >
                    View Employees
                  </Button>
                </div>
              </div>
            </CardBody>
          </Card>
        )}

        {!credentials && (
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <Card className="mb-6">
            <CardHeader>
              <h2 className="text-lg font-semibold text-gray-900">Personal Information</h2>
            </CardHeader>
            <CardBody>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <Input
                  label="Full Name *"
                  placeholder="Enter full name"
                  icon={<User className="w-5 h-5" />}
                  error={errors.name?.message}
                  {...register('name')}
                />
                <Input
                  label="Email Address *"
                  type="email"
                  placeholder="email@example.com"
                  icon={<Mail className="w-5 h-5" />}
                  error={errors.email?.message}
                  {...register('email')}
                />
                <Input
                  label="Phone Number *"
                  placeholder="1234567890"
                  icon={<Phone className="w-5 h-5" />}
                  error={errors.phone?.message}
                  {...register('phone')}
                />
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">
                    Role *
                  </label>
                  <select
                    className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-odoo-primary focus:border-transparent"
                    {...register('role')}
                  >
                    <option value="">Select Role</option>
                    <option value={USER_ROLES.EMPLOYEE}>Employee</option>
                    <option value={USER_ROLES.HR}>HR</option>
                    <option value={USER_ROLES.ADMIN}>Admin</option>
                  </select>
                  {errors.role && <p className="mt-1.5 text-sm text-danger">{errors.role.message}</p>}
                </div>
              </div>

              <div className="mt-5">
                <label className="block text-sm font-medium text-gray-700 mb-1.5">
                  Address
                </label>
                <textarea
                  rows="3"
                  placeholder="Enter full address"
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-odoo-primary focus:border-transparent"
                  {...register('address')}
                />
              </div>
            </CardBody>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <h2 className="text-lg font-semibold text-gray-900">Job Details</h2>
            </CardHeader>
            <CardBody>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                <Input
                  label="Designation *"
                  placeholder="e.g., Software Engineer"
                  icon={<Briefcase className="w-5 h-5" />}
                  error={errors.designation?.message}
                  {...register('designation')}
                />
                <Input
                  label="Department *"
                  placeholder="e.g., Engineering"
                  icon={<Briefcase className="w-5 h-5" />}
                  error={errors.department?.message}
                  {...register('department')}
                />
                <Input
                  label="Joining Date *"
                  type="date"
                  icon={<Calendar className="w-5 h-5" />}
                  error={errors.joiningDate?.message}
                  {...register('joiningDate')}
                />
                <Input
                  label="Salary *"
                  type="number"
                  placeholder="50000"
                  icon={<DollarSign className="w-5 h-5" />}
                  error={errors.salary?.message}
                  {...register('salary')}
                />
              </div>
            </CardBody>
          </Card>

          <Card className="mb-6">
            <CardHeader>
              <h2 className="text-lg font-semibold text-gray-900">Account Settings</h2>
            </CardHeader>
            <CardBody>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-sm text-blue-800">
                  <strong>Automatic Credential Generation:</strong>
                </p>
                <ul className="text-sm text-blue-700 mt-2 space-y-1 list-disc list-inside">
                  <li>Login ID will be auto-generated based on company and employee name</li>
                  <li>A secure password will be automatically created</li>
                  <li>Employee must change password on first login for security</li>
                </ul>
              </div>

              <div className="grid grid-cols-1 gap-5 mt-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">
                    Role *
                  </label>
                  <select
                    className={`w-full px-4 py-2.5 border rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-odoo-primary focus:border-transparent ${
                      errors.role ? 'border-danger' : 'border-gray-300'
                    }`}
                    {...register('role')}
                  >
                    <option value="">Select Role</option>
                    <option value="employee">Employee</option>
                    <option value="hr">HR Officer</option>
                    <option value="admin">Admin</option>
                  </select>
                  {errors.role && (
                    <p className="mt-1 text-sm text-danger">{errors.role.message}</p>
                  )}
                </div>
              </div>
            </CardBody>
          </Card>

          <div className="flex justify-end space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate('/employees')}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="primary"
              loading={isSubmitting}
              disabled={isSubmitting}
            >
              Add Employee
            </Button>
          </div>
        </form>
        )}
      </div>
    </DashboardLayout>
  )
}

export default AddEmployee
